apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Testing
on:
  push:
    branches:
      - "**"
jobs:
  test:
    steps:
      - uses: docker://puchy22/nutri-app:latest
        name: Testing code
        kind: test
        run: bun run test
