
name: Bun Canary Test

on:
  push:

jobs:
  test-canary-version:
    name: Ejecutar los tests con la versión canary de Bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary

      - run: bun run test

  test-0_8-version:
    name: Ejecutar los tests con la versión 0.8 de Bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.8

      - run: bun run test
