
name: Bun Canary Test

on:
  push:

jobs:
  test-bun-version:
    name: Ejecutar los tests con la versión canary de Bun
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [canary, 0.8]

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - run: bun run test

