
name: Publicación imagen Docker

on:
  push:
    paths:
      - 'Containerfile'
      - 'bun.lockb'
      - 'package.json'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Containerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nutri-app:latest
